apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
spec:
  restartPolicy: Always
  containers:
    - name: nginx-container
      image: nginx:1.21.1
      ports:
        - containerPort: 80
    - name: nginx-container-prior
      image: nginx:1.19.10
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: 128Gi   # Set the memory request to 64MiB for the older Nginx version
    - name: busybox-container
      image: busybox:1.33.1
      command: ["sleep", "infinity"]
