apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-replicaset
  namespace: komodor-apps
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd-container
          image: httpd:2.4.51-alpine
          ports:
            - containerPort: 80
